// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ4s1FZwsA7BW70YyRO9uEq7o_-8GuRfc',
    appId: '1:220361169145:web:62d5da9261aa04123dea28',
    messagingSenderId: '220361169145',
    projectId: 'snerky-4b62f',
    authDomain: 'snerky-4b62f.firebaseapp.com',
    storageBucket: 'snerky-4b62f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYbDStgMfMk7_KL7bQ0qyDdXb8dKQrK-o',
    appId: '1:220361169145:android:290fbac0ad22379c3dea28',
    messagingSenderId: '220361169145',
    projectId: 'snerky-4b62f',
    storageBucket: 'snerky-4b62f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfUQYzFeQUMGRwyTAlFhpmD4Wu2gLjA8M',
    appId: '1:220361169145:ios:5208c39dae36269a3dea28',
    messagingSenderId: '220361169145',
    projectId: 'snerky-4b62f',
    storageBucket: 'snerky-4b62f.appspot.com',
    iosBundleId: 'com.example.snerky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfUQYzFeQUMGRwyTAlFhpmD4Wu2gLjA8M',
    appId: '1:220361169145:ios:2d9a760612ebc0883dea28',
    messagingSenderId: '220361169145',
    projectId: 'snerky-4b62f',
    storageBucket: 'snerky-4b62f.appspot.com',
    iosBundleId: 'com.example.snerky.RunnerTests',
  );
}
