import 'package:flutter/material.dart';
import 'package:snerky/Widgets/widgets.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      initialRoute: '/',
      routes: {
        '/': (context) => Home(),
        '/Account': (context) => Account(),
        '/Checkout': (context) => Checkout(),
        '/Favorite': (context) => Favorite(),
        '/Login': (context) => Login(),
        '/SearchPage': (context) => SearchPage(),
        '/ShoppingCart': (context) => ShoppingCart(),
        '/Signin': (context) => Signin(),
      },
    );
  }
}
